// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_my.proto

package com.villa.im.model;

public final class ProtoBuf {
  private ProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface proto_myOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.villa.im.model.proto_my)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *指令类型 用于请求分发
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     *消息从那里来
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The from.
     */
    String getFrom();
    /**
     * <pre>
     *消息从那里来
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The bytes for from.
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     *消息转发目标
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    String getTo();
    /**
     * <pre>
     *消息转发目标
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>string dataContent = 4;</code>
     * @return The dataContent.
     */
    String getDataContent();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>string dataContent = 4;</code>
     * @return The bytes for dataContent.
     */
    com.google.protobuf.ByteString
        getDataContentBytes();

    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgNo = 5;</code>
     * @return The msgNo.
     */
    String getMsgNo();
    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgNo = 5;</code>
     * @return The bytes for msgNo.
     */
    com.google.protobuf.ByteString
        getMsgNoBytes();

    /**
     * <pre>
     *-1 此消息不是ack应答包  1-此消息是ack应答包
     * </pre>
     *
     * <code>int32 ack = 6;</code>
     * @return The ack.
     */
    int getAck();
  }
  /**
   * Protobuf type {@code com.villa.im.model.proto_my}
   */
  public static final class proto_my extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.villa.im.model.proto_my)
      proto_myOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use proto_my.newBuilder() to construct.
    private proto_my(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private proto_my() {
      from_ = "";
      to_ = "";
      dataContent_ = "";
      msgNo_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new proto_my();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private proto_my(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              dataContent_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              msgNo_ = s;
              break;
            }
            case 48: {

              ack_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBuf.internal_static_com_villa_im_model_proto_my_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBuf.internal_static_com_villa_im_model_proto_my_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_my.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *指令类型 用于请求分发
     * </pre>
     *
     * <code>int32 type = 1;</code>
     * @return The type.
     */
    @Override
    public int getType() {
      return type_;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private volatile Object from_;
    /**
     * <pre>
     *消息从那里来
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The from.
     */
    @Override
    public String getFrom() {
      Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息从那里来
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The bytes for from.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile Object to_;
    /**
     * <pre>
     *消息转发目标
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    @Override
    public String getTo() {
      Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息转发目标
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    @Override
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATACONTENT_FIELD_NUMBER = 4;
    private volatile Object dataContent_;
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>string dataContent = 4;</code>
     * @return The dataContent.
     */
    @Override
    public String getDataContent() {
      Object ref = dataContent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataContent_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>string dataContent = 4;</code>
     * @return The bytes for dataContent.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataContentBytes() {
      Object ref = dataContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGNO_FIELD_NUMBER = 5;
    private volatile Object msgNo_;
    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgNo = 5;</code>
     * @return The msgNo.
     */
    @Override
    public String getMsgNo() {
      Object ref = msgNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgNo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息编号
     * </pre>
     *
     * <code>string msgNo = 5;</code>
     * @return The bytes for msgNo.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgNoBytes() {
      Object ref = msgNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACK_FIELD_NUMBER = 6;
    private int ack_;
    /**
     * <pre>
     *-1 此消息不是ack应答包  1-此消息是ack应答包
     * </pre>
     *
     * <code>int32 ack = 6;</code>
     * @return The ack.
     */
    @Override
    public int getAck() {
      return ack_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (!getDataContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataContent_);
      }
      if (!getMsgNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgNo_);
      }
      if (ack_ != 0) {
        output.writeInt32(6, ack_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      if (!getDataContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataContent_);
      }
      if (!getMsgNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgNo_);
      }
      if (ack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ack_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto_my)) {
        return super.equals(obj);
      }
      proto_my other = (proto_my) obj;

      if (getType()
          != other.getType()) return false;
      if (!getFrom()
          .equals(other.getFrom())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getDataContent()
          .equals(other.getDataContent())) return false;
      if (!getMsgNo()
          .equals(other.getMsgNo())) return false;
      if (getAck()
          != other.getAck()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + DATACONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getDataContent().hashCode();
      hash = (37 * hash) + MSGNO_FIELD_NUMBER;
      hash = (53 * hash) + getMsgNo().hashCode();
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + getAck();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto_my parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_my parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_my parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_my parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_my parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto_my parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto_my parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_my parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_my parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto_my parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto_my parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto_my parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto_my prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.villa.im.model.proto_my}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.villa.im.model.proto_my)
        proto_myOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBuf.internal_static_com_villa_im_model_proto_my_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBuf.internal_static_com_villa_im_model_proto_my_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto_my.class, Builder.class);
      }

      // Construct using com.villa.im.model.ProtoBuf.proto_my.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        from_ = "";

        to_ = "";

        dataContent_ = "";

        msgNo_ = "";

        ack_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBuf.internal_static_com_villa_im_model_proto_my_descriptor;
      }

      @Override
      public proto_my getDefaultInstanceForType() {
        return proto_my.getDefaultInstance();
      }

      @Override
      public proto_my build() {
        proto_my result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public proto_my buildPartial() {
        proto_my result = new proto_my(this);
        result.type_ = type_;
        result.from_ = from_;
        result.to_ = to_;
        result.dataContent_ = dataContent_;
        result.msgNo_ = msgNo_;
        result.ack_ = ack_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto_my) {
          return mergeFrom((proto_my)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto_my other) {
        if (other == proto_my.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getDataContent().isEmpty()) {
          dataContent_ = other.dataContent_;
          onChanged();
        }
        if (!other.getMsgNo().isEmpty()) {
          msgNo_ = other.msgNo_;
          onChanged();
        }
        if (other.getAck() != 0) {
          setAck(other.getAck());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto_my parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto_my) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *指令类型 用于请求分发
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *指令类型 用于请求分发
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *指令类型 用于请求分发
       * </pre>
       *
       * <code>int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object from_ = "";
      /**
       * <pre>
       *消息从那里来
       * </pre>
       *
       * <code>string from = 2;</code>
       * @return The from.
       */
      public String getFrom() {
        Object ref = from_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息从那里来
       * </pre>
       *
       * <code>string from = 2;</code>
       * @return The bytes for from.
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息从那里来
       * </pre>
       *
       * <code>string from = 2;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息从那里来
       * </pre>
       *
       * <code>string from = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息从那里来
       * </pre>
       *
       * <code>string from = 2;</code>
       * @param value The bytes for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private Object to_ = "";
      /**
       * <pre>
       *消息转发目标
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return The to.
       */
      public String getTo() {
        Object ref = to_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息转发目标
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息转发目标
       * </pre>
       *
       * <code>string to = 3;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息转发目标
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息转发目标
       * </pre>
       *
       * <code>string to = 3;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private Object dataContent_ = "";
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>string dataContent = 4;</code>
       * @return The dataContent.
       */
      public String getDataContent() {
        Object ref = dataContent_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataContent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>string dataContent = 4;</code>
       * @return The bytes for dataContent.
       */
      public com.google.protobuf.ByteString
          getDataContentBytes() {
        Object ref = dataContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>string dataContent = 4;</code>
       * @param value The dataContent to set.
       * @return This builder for chaining.
       */
      public Builder setDataContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>string dataContent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataContent() {
        
        dataContent_ = getDefaultInstance().getDataContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>string dataContent = 4;</code>
       * @param value The bytes for dataContent to set.
       * @return This builder for chaining.
       */
      public Builder setDataContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataContent_ = value;
        onChanged();
        return this;
      }

      private Object msgNo_ = "";
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgNo = 5;</code>
       * @return The msgNo.
       */
      public String getMsgNo() {
        Object ref = msgNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgNo = 5;</code>
       * @return The bytes for msgNo.
       */
      public com.google.protobuf.ByteString
          getMsgNoBytes() {
        Object ref = msgNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgNo = 5;</code>
       * @param value The msgNo to set.
       * @return This builder for chaining.
       */
      public Builder setMsgNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgNo = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgNo() {
        
        msgNo_ = getDefaultInstance().getMsgNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息编号
       * </pre>
       *
       * <code>string msgNo = 5;</code>
       * @param value The bytes for msgNo to set.
       * @return This builder for chaining.
       */
      public Builder setMsgNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgNo_ = value;
        onChanged();
        return this;
      }

      private int ack_ ;
      /**
       * <pre>
       *-1 此消息不是ack应答包  1-此消息是ack应答包
       * </pre>
       *
       * <code>int32 ack = 6;</code>
       * @return The ack.
       */
      @Override
      public int getAck() {
        return ack_;
      }
      /**
       * <pre>
       *-1 此消息不是ack应答包  1-此消息是ack应答包
       * </pre>
       *
       * <code>int32 ack = 6;</code>
       * @param value The ack to set.
       * @return This builder for chaining.
       */
      public Builder setAck(int value) {
        
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *-1 此消息不是ack应答包  1-此消息是ack应答包
       * </pre>
       *
       * <code>int32 ack = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAck() {
        
        ack_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.villa.im.model.proto_my)
    }

    // @@protoc_insertion_point(class_scope:com.villa.im.model.proto_my)
    private static final proto_my DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto_my();
    }

    public static proto_my getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<proto_my>
        PARSER = new com.google.protobuf.AbstractParser<proto_my>() {
      @Override
      public proto_my parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new proto_my(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<proto_my> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<proto_my> getParserForType() {
      return PARSER;
    }

    @Override
    public proto_my getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_villa_im_model_proto_my_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_villa_im_model_proto_my_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016proto_my.proto\022\022com.villa.im.model\"c\n\010" +
      "proto_my\022\014\n\004type\030\001 \001(\005\022\014\n\004from\030\002 \001(\t\022\n\n\002" +
      "to\030\003 \001(\t\022\023\n\013dataContent\030\004 \001(\t\022\r\n\005msgNo\030\005" +
      " \001(\t\022\013\n\003ack\030\006 \001(\005B\036\n\022com.villa.im.modelB" +
      "\010ProtoBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_villa_im_model_proto_my_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_villa_im_model_proto_my_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_villa_im_model_proto_my_descriptor,
        new String[] { "Type", "From", "To", "DataContent", "MsgNo", "Ack", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
