// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_my.proto

package com.villa.im.model;

public final class ProtoBuf {
    private ProtoBuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface proto_myOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.villa.im.model.proto_my)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 指令类型 用于请求分发
         * </pre>
         *
         * <code>int32 type = 1;</code>
         *
         * @return The type.
         */
        int getType();

        /**
         * <pre>
         * 消息从那里来
         * </pre>
         *
         * <code>string from = 2;</code>
         *
         * @return The from.
         */
        String getFrom();

        /**
         * <pre>
         * 消息从那里来
         * </pre>
         *
         * <code>string from = 2;</code>
         *
         * @return The bytes for from.
         */
        com.google.protobuf.ByteString
        getFromBytes();

        /**
         * <pre>
         * 消息转发目标
         * </pre>
         *
         * <code>string to = 3;</code>
         *
         * @return The to.
         */
        String getTo();

        /**
         * <pre>
         * 消息转发目标
         * </pre>
         *
         * <code>string to = 3;</code>
         *
         * @return The bytes for to.
         */
        com.google.protobuf.ByteString
        getToBytes();

        /**
         * <pre>
         * 消息体
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The data.
         */
        String getData();

        /**
         * <pre>
         * 消息体
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The bytes for data.
         */
        com.google.protobuf.ByteString
        getDataBytes();

        /**
         * <pre>
         * 消息编号
         * </pre>
         *
         * <code>string no = 5;</code>
         *
         * @return The no.
         */
        String getNo();

        /**
         * <pre>
         * 消息编号
         * </pre>
         *
         * <code>string no = 5;</code>
         *
         * @return The bytes for no.
         */
        com.google.protobuf.ByteString
        getNoBytes();

        /**
         * <pre>
         * -1 此消息不是ack应答包  1-此消息是ack应答包
         * </pre>
         *
         * <code>int32 ack = 6;</code>
         *
         * @return The ack.
         */
        int getAck();

        /**
         * <code>string ext1 = 7;</code>
         *
         * @return The ext1.
         */
        String getExt1();

        /**
         * <code>string ext1 = 7;</code>
         *
         * @return The bytes for ext1.
         */
        com.google.protobuf.ByteString
        getExt1Bytes();

        /**
         * <code>string ext2 = 8;</code>
         *
         * @return The ext2.
         */
        String getExt2();

        /**
         * <code>string ext2 = 8;</code>
         *
         * @return The bytes for ext2.
         */
        com.google.protobuf.ByteString
        getExt2Bytes();

        /**
         * <code>string ext3 = 9;</code>
         *
         * @return The ext3.
         */
        String getExt3();

        /**
         * <code>string ext3 = 9;</code>
         *
         * @return The bytes for ext3.
         */
        com.google.protobuf.ByteString
        getExt3Bytes();

        /**
         * <code>int32 ext4 = 10;</code>
         *
         * @return The ext4.
         */
        int getExt4();

        /**
         * <code>int32 ext5 = 11;</code>
         *
         * @return The ext5.
         */
        int getExt5();
    }

    /**
     * Protobuf type {@code com.villa.im.model.proto_my}
     */
    public static final class proto_my extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.villa.im.model.proto_my)
            proto_myOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use proto_my.newBuilder() to construct.
        private proto_my(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private proto_my() {
            from_ = "";
            to_ = "";
            data_ = "";
            no_ = "";
            ext1_ = "";
            ext2_ = "";
            ext3_ = "";
        }


        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new proto_my();
        }


        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private proto_my(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            type_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            from_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            to_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            data_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            no_ = s;
                            break;
                        }
                        case 48: {

                            ack_ = input.readInt32();
                            break;
                        }
                        case 58: {
                            String s = input.readStringRequireUtf8();

                            ext1_ = s;
                            break;
                        }
                        case 66: {
                            String s = input.readStringRequireUtf8();

                            ext2_ = s;
                            break;
                        }
                        case 74: {
                            String s = input.readStringRequireUtf8();

                            ext3_ = s;
                            break;
                        }
                        case 80: {

                            ext4_ = input.readInt32();
                            break;
                        }
                        case 88: {

                            ext5_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoBuf.internal_static_com_villa_im_model_proto_my_descriptor;
        }


        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoBuf.internal_static_com_villa_im_model_proto_my_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            proto_my.class, Builder.class);
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        /**
         * <pre>
         * 指令类型 用于请求分发
         * </pre>
         *
         * <code>int32 type = 1;</code>
         *
         * @return The type.
         */

        public int getType() {
            return type_;
        }

        public static final int FROM_FIELD_NUMBER = 2;
        private volatile Object from_;

        /**
         * <pre>
         * 消息从那里来
         * </pre>
         *
         * <code>string from = 2;</code>
         *
         * @return The from.
         */

        public String getFrom() {
            Object ref = from_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                from_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 消息从那里来
         * </pre>
         *
         * <code>string from = 2;</code>
         *
         * @return The bytes for from.
         */

        public com.google.protobuf.ByteString
        getFromBytes() {
            Object ref = from_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                from_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TO_FIELD_NUMBER = 3;
        private volatile Object to_;

        /**
         * <pre>
         * 消息转发目标
         * </pre>
         *
         * <code>string to = 3;</code>
         *
         * @return The to.
         */

        public String getTo() {
            Object ref = to_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                to_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 消息转发目标
         * </pre>
         *
         * <code>string to = 3;</code>
         *
         * @return The bytes for to.
         */

        public com.google.protobuf.ByteString
        getToBytes() {
            Object ref = to_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                to_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATA_FIELD_NUMBER = 4;
        private volatile Object data_;

        /**
         * <pre>
         * 消息体
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The data.
         */

        public String getData() {
            Object ref = data_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                data_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 消息体
         * </pre>
         *
         * <code>string data = 4;</code>
         *
         * @return The bytes for data.
         */

        public com.google.protobuf.ByteString
        getDataBytes() {
            Object ref = data_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                data_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NO_FIELD_NUMBER = 5;
        private volatile Object no_;

        /**
         * <pre>
         * 消息编号
         * </pre>
         *
         * <code>string no = 5;</code>
         *
         * @return The no.
         */

        public String getNo() {
            Object ref = no_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                no_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 消息编号
         * </pre>
         *
         * <code>string no = 5;</code>
         *
         * @return The bytes for no.
         */

        public com.google.protobuf.ByteString
        getNoBytes() {
            Object ref = no_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                no_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ACK_FIELD_NUMBER = 6;
        private int ack_;

        /**
         * <pre>
         * -1 此消息不是ack应答包  1-此消息是ack应答包
         * </pre>
         *
         * <code>int32 ack = 6;</code>
         *
         * @return The ack.
         */

        public int getAck() {
            return ack_;
        }

        public static final int EXT1_FIELD_NUMBER = 7;
        private volatile Object ext1_;

        /**
         * <code>string ext1 = 7;</code>
         *
         * @return The ext1.
         */

        public String getExt1() {
            Object ref = ext1_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ext1_ = s;
                return s;
            }
        }

        /**
         * <code>string ext1 = 7;</code>
         *
         * @return The bytes for ext1.
         */

        public com.google.protobuf.ByteString
        getExt1Bytes() {
            Object ref = ext1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ext1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EXT2_FIELD_NUMBER = 8;
        private volatile Object ext2_;

        /**
         * <code>string ext2 = 8;</code>
         *
         * @return The ext2.
         */

        public String getExt2() {
            Object ref = ext2_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ext2_ = s;
                return s;
            }
        }

        /**
         * <code>string ext2 = 8;</code>
         *
         * @return The bytes for ext2.
         */

        public com.google.protobuf.ByteString
        getExt2Bytes() {
            Object ref = ext2_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ext2_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EXT3_FIELD_NUMBER = 9;
        private volatile Object ext3_;

        /**
         * <code>string ext3 = 9;</code>
         *
         * @return The ext3.
         */

        public String getExt3() {
            Object ref = ext3_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ext3_ = s;
                return s;
            }
        }

        /**
         * <code>string ext3 = 9;</code>
         *
         * @return The bytes for ext3.
         */

        public com.google.protobuf.ByteString
        getExt3Bytes() {
            Object ref = ext3_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ext3_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EXT4_FIELD_NUMBER = 10;
        private int ext4_;

        /**
         * <code>int32 ext4 = 10;</code>
         *
         * @return The ext4.
         */

        public int getExt4() {
            return ext4_;
        }

        public static final int EXT5_FIELD_NUMBER = 11;
        private int ext5_;

        /**
         * <code>int32 ext5 = 11;</code>
         *
         * @return The ext5.
         */

        public int getExt5() {
            return ext5_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }


        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != 0) {
                output.writeInt32(1, type_);
            }
            if (!getFromBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
            }
            if (!getToBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
            }
            if (!getDataBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
            }
            if (!getNoBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, no_);
            }
            if (ack_ != 0) {
                output.writeInt32(6, ack_);
            }
            if (!getExt1Bytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ext1_);
            }
            if (!getExt2Bytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, ext2_);
            }
            if (!getExt3Bytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ext3_);
            }
            if (ext4_ != 0) {
                output.writeInt32(10, ext4_);
            }
            if (ext5_ != 0) {
                output.writeInt32(11, ext5_);
            }
            unknownFields.writeTo(output);
        }


        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, type_);
            }
            if (!getFromBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
            }
            if (!getToBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
            }
            if (!getDataBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
            }
            if (!getNoBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, no_);
            }
            if (ack_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, ack_);
            }
            if (!getExt1Bytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ext1_);
            }
            if (!getExt2Bytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, ext2_);
            }
            if (!getExt3Bytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ext3_);
            }
            if (ext4_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(10, ext4_);
            }
            if (ext5_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(11, ext5_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }


        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof proto_my)) {
                return super.equals(obj);
            }
            proto_my other = (proto_my) obj;

            if (getType()
                    != other.getType()) return false;
            if (!getFrom()
                    .equals(other.getFrom())) return false;
            if (!getTo()
                    .equals(other.getTo())) return false;
            if (!getData()
                    .equals(other.getData())) return false;
            if (!getNo()
                    .equals(other.getNo())) return false;
            if (getAck()
                    != other.getAck()) return false;
            if (!getExt1()
                    .equals(other.getExt1())) return false;
            if (!getExt2()
                    .equals(other.getExt2())) return false;
            if (!getExt3()
                    .equals(other.getExt3())) return false;
            if (getExt4()
                    != other.getExt4()) return false;
            if (getExt5()
                    != other.getExt5()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }


        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + FROM_FIELD_NUMBER;
            hash = (53 * hash) + getFrom().hashCode();
            hash = (37 * hash) + TO_FIELD_NUMBER;
            hash = (53 * hash) + getTo().hashCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (37 * hash) + NO_FIELD_NUMBER;
            hash = (53 * hash) + getNo().hashCode();
            hash = (37 * hash) + ACK_FIELD_NUMBER;
            hash = (53 * hash) + getAck();
            hash = (37 * hash) + EXT1_FIELD_NUMBER;
            hash = (53 * hash) + getExt1().hashCode();
            hash = (37 * hash) + EXT2_FIELD_NUMBER;
            hash = (53 * hash) + getExt2().hashCode();
            hash = (37 * hash) + EXT3_FIELD_NUMBER;
            hash = (53 * hash) + getExt3().hashCode();
            hash = (37 * hash) + EXT4_FIELD_NUMBER;
            hash = (53 * hash) + getExt4();
            hash = (37 * hash) + EXT5_FIELD_NUMBER;
            hash = (53 * hash) + getExt5();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static proto_my parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static proto_my parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static proto_my parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static proto_my parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static proto_my parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static proto_my parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static proto_my parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static proto_my parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static proto_my parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static proto_my parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static proto_my parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static proto_my parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }


        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(proto_my prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }


        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.villa.im.model.proto_my}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.villa.im.model.proto_my)
                proto_myOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoBuf.internal_static_com_villa_im_model_proto_my_descriptor;
            }


            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoBuf.internal_static_com_villa_im_model_proto_my_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                proto_my.class, Builder.class);
            }

            // Construct using com.villa.im.model.ProtoBuf.proto_my.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = 0;

                from_ = "";

                to_ = "";

                data_ = "";

                no_ = "";

                ack_ = 0;

                ext1_ = "";

                ext2_ = "";

                ext3_ = "";

                ext4_ = 0;

                ext5_ = 0;

                return this;
            }


            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoBuf.internal_static_com_villa_im_model_proto_my_descriptor;
            }


            public proto_my getDefaultInstanceForType() {
                return proto_my.getDefaultInstance();
            }


            public proto_my build() {
                proto_my result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }


            public proto_my buildPartial() {
                proto_my result = new proto_my(this);
                result.type_ = type_;
                result.from_ = from_;
                result.to_ = to_;
                result.data_ = data_;
                result.no_ = no_;
                result.ack_ = ack_;
                result.ext1_ = ext1_;
                result.ext2_ = ext2_;
                result.ext3_ = ext3_;
                result.ext4_ = ext4_;
                result.ext5_ = ext5_;
                onBuilt();
                return result;
            }


            public Builder clone() {
                return super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof proto_my) {
                    return mergeFrom((proto_my) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(proto_my other) {
                if (other == proto_my.getDefaultInstance()) return this;
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (!other.getFrom().isEmpty()) {
                    from_ = other.from_;
                    onChanged();
                }
                if (!other.getTo().isEmpty()) {
                    to_ = other.to_;
                    onChanged();
                }
                if (!other.getData().isEmpty()) {
                    data_ = other.data_;
                    onChanged();
                }
                if (!other.getNo().isEmpty()) {
                    no_ = other.no_;
                    onChanged();
                }
                if (other.getAck() != 0) {
                    setAck(other.getAck());
                }
                if (!other.getExt1().isEmpty()) {
                    ext1_ = other.ext1_;
                    onChanged();
                }
                if (!other.getExt2().isEmpty()) {
                    ext2_ = other.ext2_;
                    onChanged();
                }
                if (!other.getExt3().isEmpty()) {
                    ext3_ = other.ext3_;
                    onChanged();
                }
                if (other.getExt4() != 0) {
                    setExt4(other.getExt4());
                }
                if (other.getExt5() != 0) {
                    setExt5(other.getExt5());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }


            public final boolean isInitialized() {
                return true;
            }


            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                proto_my parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (proto_my) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int type_;

            /**
             * <pre>
             * 指令类型 用于请求分发
             * </pre>
             *
             * <code>int32 type = 1;</code>
             *
             * @return The type.
             */

            public int getType() {
                return type_;
            }

            /**
             * <pre>
             * 指令类型 用于请求分发
             * </pre>
             *
             * <code>int32 type = 1;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 指令类型 用于请求分发
             * </pre>
             *
             * <code>int32 type = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private Object from_ = "";

            /**
             * <pre>
             * 消息从那里来
             * </pre>
             *
             * <code>string from = 2;</code>
             *
             * @return The from.
             */
            public String getFrom() {
                Object ref = from_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    from_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 消息从那里来
             * </pre>
             *
             * <code>string from = 2;</code>
             *
             * @return The bytes for from.
             */
            public com.google.protobuf.ByteString
            getFromBytes() {
                Object ref = from_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    from_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 消息从那里来
             * </pre>
             *
             * <code>string from = 2;</code>
             *
             * @param value The from to set.
             * @return This builder for chaining.
             */
            public Builder setFrom(
                    String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                from_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息从那里来
             * </pre>
             *
             * <code>string from = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearFrom() {

                from_ = getDefaultInstance().getFrom();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息从那里来
             * </pre>
             *
             * <code>string from = 2;</code>
             *
             * @param value The bytes for from to set.
             * @return This builder for chaining.
             */
            public Builder setFromBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                from_ = value;
                onChanged();
                return this;
            }

            private Object to_ = "";

            /**
             * <pre>
             * 消息转发目标
             * </pre>
             *
             * <code>string to = 3;</code>
             *
             * @return The to.
             */
            public String getTo() {
                Object ref = to_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    to_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 消息转发目标
             * </pre>
             *
             * <code>string to = 3;</code>
             *
             * @return The bytes for to.
             */
            public com.google.protobuf.ByteString
            getToBytes() {
                Object ref = to_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    to_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 消息转发目标
             * </pre>
             *
             * <code>string to = 3;</code>
             *
             * @param value The to to set.
             * @return This builder for chaining.
             */
            public Builder setTo(
                    String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                to_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息转发目标
             * </pre>
             *
             * <code>string to = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTo() {

                to_ = getDefaultInstance().getTo();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息转发目标
             * </pre>
             *
             * <code>string to = 3;</code>
             *
             * @param value The bytes for to to set.
             * @return This builder for chaining.
             */
            public Builder setToBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                to_ = value;
                onChanged();
                return this;
            }

            private Object data_ = "";

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @return The data.
             */
            public String getData() {
                Object ref = data_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    data_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @return The bytes for data.
             */
            public com.google.protobuf.ByteString
            getDataBytes() {
                Object ref = data_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    data_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(
                    String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>string data = 4;</code>
             *
             * @param value The bytes for data to set.
             * @return This builder for chaining.
             */
            public Builder setDataBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                data_ = value;
                onChanged();
                return this;
            }

            private Object no_ = "";

            /**
             * <pre>
             * 消息编号
             * </pre>
             *
             * <code>string no = 5;</code>
             *
             * @return The no.
             */
            public String getNo() {
                Object ref = no_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    no_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 消息编号
             * </pre>
             *
             * <code>string no = 5;</code>
             *
             * @return The bytes for no.
             */
            public com.google.protobuf.ByteString
            getNoBytes() {
                Object ref = no_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    no_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 消息编号
             * </pre>
             *
             * <code>string no = 5;</code>
             *
             * @param value The no to set.
             * @return This builder for chaining.
             */
            public Builder setNo(
                    String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                no_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息编号
             * </pre>
             *
             * <code>string no = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearNo() {

                no_ = getDefaultInstance().getNo();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息编号
             * </pre>
             *
             * <code>string no = 5;</code>
             *
             * @param value The bytes for no to set.
             * @return This builder for chaining.
             */
            public Builder setNoBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                no_ = value;
                onChanged();
                return this;
            }

            private int ack_;

            /**
             * <pre>
             * -1 此消息不是ack应答包  1-此消息是ack应答包
             * </pre>
             *
             * <code>int32 ack = 6;</code>
             *
             * @return The ack.
             */

            public int getAck() {
                return ack_;
            }

            /**
             * <pre>
             * -1 此消息不是ack应答包  1-此消息是ack应答包
             * </pre>
             *
             * <code>int32 ack = 6;</code>
             *
             * @param value The ack to set.
             * @return This builder for chaining.
             */
            public Builder setAck(int value) {
                ack_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * -1 此消息不是ack应答包  1-此消息是ack应答包
             * </pre>
             *
             * <code>int32 ack = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAck() {

                ack_ = 0;
                onChanged();
                return this;
            }

            private Object ext1_ = "";

            /**
             * <code>string ext1 = 7;</code>
             *
             * @return The ext1.
             */
            public String getExt1() {
                Object ref = ext1_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ext1_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string ext1 = 7;</code>
             *
             * @return The bytes for ext1.
             */
            public com.google.protobuf.ByteString
            getExt1Bytes() {
                Object ref = ext1_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ext1_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string ext1 = 7;</code>
             *
             * @param value The ext1 to set.
             * @return This builder for chaining.
             */
            public Builder setExt1(String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                ext1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string ext1 = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearExt1() {

                ext1_ = getDefaultInstance().getExt1();
                onChanged();
                return this;
            }

            /**
             * <code>string ext1 = 7;</code>
             *
             * @param value The bytes for ext1 to set.
             * @return This builder for chaining.
             */
            public Builder setExt1Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ext1_ = value;
                onChanged();
                return this;
            }

            private Object ext2_ = "";

            /**
             * <code>string ext2 = 8;</code>
             *
             * @return The ext2.
             */
            public String getExt2() {
                Object ref = ext2_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ext2_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string ext2 = 8;</code>
             *
             * @return The bytes for ext2.
             */
            public com.google.protobuf.ByteString
            getExt2Bytes() {
                Object ref = ext2_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ext2_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string ext2 = 8;</code>
             *
             * @param value The ext2 to set.
             * @return This builder for chaining.
             */
            public Builder setExt2(
                    String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                ext2_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string ext2 = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearExt2() {

                ext2_ = getDefaultInstance().getExt2();
                onChanged();
                return this;
            }

            /**
             * <code>string ext2 = 8;</code>
             *
             * @param value The bytes for ext2 to set.
             * @return This builder for chaining.
             */
            public Builder setExt2Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ext2_ = value;
                onChanged();
                return this;
            }

            private Object ext3_ = "";

            /**
             * <code>string ext3 = 9;</code>
             *
             * @return The ext3.
             */
            public String getExt3() {
                Object ref = ext3_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ext3_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string ext3 = 9;</code>
             *
             * @return The bytes for ext3.
             */
            public com.google.protobuf.ByteString
            getExt3Bytes() {
                Object ref = ext3_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ext3_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string ext3 = 9;</code>
             *
             * @param value The ext3 to set.
             * @return This builder for chaining.
             */
            public Builder setExt3(
                    String value) {
                if (value == null) {
                  return this;
//                    throw new NullPointerException();
                }

                ext3_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string ext3 = 9;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearExt3() {

                ext3_ = getDefaultInstance().getExt3();
                onChanged();
                return this;
            }

            /**
             * <code>string ext3 = 9;</code>
             *
             * @param value The bytes for ext3 to set.
             * @return This builder for chaining.
             */
            public Builder setExt3Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ext3_ = value;
                onChanged();
                return this;
            }

            private int ext4_;

            /**
             * <code>int32 ext4 = 10;</code>
             *
             * @return The ext4.
             */

            public int getExt4() {
                return ext4_;
            }

            /**
             * <code>int32 ext4 = 10;</code>
             *
             * @param value The ext4 to set.
             * @return This builder for chaining.
             */
            public Builder setExt4(Integer value) {
                if(value==null)return this;
                ext4_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 ext4 = 10;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearExt4() {

                ext4_ = 0;
                onChanged();
                return this;
            }

            private int ext5_;

            /**
             * <code>int32 ext5 = 11;</code>
             *
             * @return The ext5.
             */

            public int getExt5() {
                return ext5_;
            }

            /**
             * <code>int32 ext5 = 11;</code>
             *
             * @param value The ext5 to set.
             * @return This builder for chaining.
             */
            public Builder setExt5(Integer value) {
                if(value==null)return this;
                ext5_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 ext5 = 11;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearExt5() {

                ext5_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }


            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.villa.im.model.proto_my)
        }

        // @@protoc_insertion_point(class_scope:com.villa.im.model.proto_my)
        private static final proto_my DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new proto_my();
        }

        public static proto_my getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<proto_my>
                PARSER = new com.google.protobuf.AbstractParser<proto_my>() {

            public proto_my parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new proto_my(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<proto_my> parser() {
            return PARSER;
        }


        public com.google.protobuf.Parser<proto_my> getParserForType() {
            return PARSER;
        }


        public proto_my getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_villa_im_model_proto_my_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_villa_im_model_proto_my_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016proto_my.proto\022\022com.villa.im.model\"\237\001\n" +
                        "\010proto_my\022\014\n\004type\030\001 \001(\005\022\014\n\004from\030\002 \001(\t\022\n\n" +
                        "\002to\030\003 \001(\t\022\014\n\004data\030\004 \001(\t\022\n\n\002no\030\005 \001(\t\022\013\n\003a" +
                        "ck\030\006 \001(\005\022\014\n\004ext1\030\007 \001(\t\022\014\n\004ext2\030\010 \001(\t\022\014\n\004" +
                        "ext3\030\t \001(\t\022\014\n\004ext4\030\n \001(\005\022\014\n\004ext5\030\013 \001(\005B\036" +
                        "\n\022com.villa.im.modelB\010ProtoBufb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_villa_im_model_proto_my_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_villa_im_model_proto_my_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_villa_im_model_proto_my_descriptor,
                new String[]{"Type", "From", "To", "Data", "No", "Ack", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
